# Provide the home page for *your* project:
homepage: "https://my-api.example.com"

# Provide the e-mail for the primary contact and others:
# Un-comment the below lines to make auto-cc work.
primary_contact: "mclow.lists@gmail.com"
auto_ccs:  
  - "eric@efcs.ca"

# We don't run this example project for real. (Don't use this flag for your project)
disabled: false
